// src/lib/bossIconMap.ts

// Map boss names (as they come from the hiscores/Wise Old Man API) → local icon path
export const bossIconMap: Record<string, string> = {
  "Abyssal Sire": "/assets/icons/bosses/abyssal_sire.png",
  "Alchemical Hydra": "/assets/icons/bosses/alchemical_hydra.png",
  "Amoxliatl": "/assets/icons/bosses/amoxliatl.png",
  "Araxxor": "/assets/icons/bosses/araxxor.png",
  "Artio": "/assets/icons/bosses/artio.png",
  "Barrows Chests": "/assets/icons/bosses/barrows_chests.png",
  "Bryophyta": "/assets/icons/bosses/bryophyta.png",
  "Callisto": "/assets/icons/bosses/callisto.png",
  "Calvar'ion": "/assets/icons/bosses/calvarion.png",
  "Cerberus": "/assets/icons/bosses/cerberus.png",
  "Chambers of Xeric": "/assets/icons/bosses/chambers_of_xeric.png",
  "Chambers of Xeric: Challenge Mode":
    "/assets/icons/bosses/chambers_of_xeric_challenge_mode.png",
  "Chaos Elemental": "/assets/icons/bosses/chaos_elemental.png",
  "Chaos Fanatic": "/assets/icons/bosses/chaos_fanatic.png",
  "Commander Zilyana": "/assets/icons/bosses/commander_zilyana.png",
  "Corporeal Beast": "/assets/icons/bosses/corporeal_beast.png",
  "Crazy Archaeologist": "/assets/icons/bosses/crazy_archaeologist.png",
  "Dagannoth Prime": "/assets/icons/bosses/dagannoth_prime.png",
  "Dagannoth Rex": "/assets/icons/bosses/dagannoth_rex.png",
  "Dagannoth Supreme": "/assets/icons/bosses/dagannoth_supreme.png",
  "Deranged Archaeologist": "/assets/icons/bosses/deranged_archaeologist.png",
  "Duke Sucellus": "/assets/icons/bosses/duke_sucellus.png",
  "General Graardor": "/assets/icons/bosses/general_graardor.png",
  "Giant Mole": "/assets/icons/bosses/giant_mole.png",
  "Grotesque Guardians": "/assets/icons/bosses/grotesque_guardians.png",
  "Hespori": "/assets/icons/bosses/hespori.png",
  "Hueycoatl": "/assets/icons/bosses/hueycoatl.png",
  "Kalphite Queen": "/assets/icons/bosses/kalphite_queen.png",
  "King Black Dragon": "/assets/icons/bosses/king_black_dragon.png",
  "Kraken": "/assets/icons/bosses/kraken.png",
  "Kree'Arra": "/assets/icons/bosses/kreearra.png",
  "K'ril Tsutsaroth": "/assets/icons/bosses/kril_tsutsaroth.png",
  "Leviathan": "/assets/icons/bosses/leviathan.png",
  "Mimic": "/assets/icons/bosses/mimic.png",
  "Nex": "/assets/icons/bosses/nex.png",
  "The Nightmare": "/assets/icons/bosses/nightmare.png",
  "Phosani's Nightmare": "/assets/icons/bosses/phosanis_nightmare.png",
  "Obor": "/assets/icons/bosses/obor.png",
  "Phantom Muspah": "/assets/icons/bosses/phantom_muspah.png",
  "Royal Titans": "/assets/icons/bosses/royal_titans.png",
  "Sarachnis": "/assets/icons/bosses/sarachnis.png",
  "Scorpia": "/assets/icons/bosses/scorpia.png",
  "Scurrius": "/assets/icons/bosses/scurrius.png",
  "Skotizo": "/assets/icons/bosses/skotizo.png",
  "Sol Heredit": "/assets/icons/bosses/sol_heredit.png",
  "Spindel": "/assets/icons/bosses/spindel.png",
  "Tempoross": "/assets/icons/bosses/tempoross.png",
  "The Gauntlet": "/assets/icons/bosses/the_gauntlet.png",
  "The Corrupted Gauntlet": "/assets/icons/bosses/the_corrupted_gauntlet.png",
  "Theatre of Blood": "/assets/icons/bosses/theatre_of_blood.png",
  "Theatre of Blood: Hard Mode":
    "/assets/icons/bosses/theatre_of_blood_hard_mode.png",
  "Thermonuclear Smoke Devil":
    "/assets/icons/bosses/thermonuclear_smoke_devil.png",
  "Tombs of Amascut": "/assets/icons/bosses/tombs_of_amascut.png",
  "Tombs of Amascut: Expert Mode":
    "/assets/icons/bosses/tombs_of_amascut_expert.png",
  "TzKal-Zuk": "/assets/icons/bosses/tzkal_zuk.png",
  "TzTok-Jad": "/assets/icons/bosses/tz_tok_jad.png",
  "Vardorvis": "/assets/icons/bosses/vardorvis.png",
  "Venenatis": "/assets/icons/bosses/venenatis.png",
  "Vet'ion": "/assets/icons/bosses/vetion.png",
  "Vorkath": "/assets/icons/bosses/vorkath.png",
  "The Whisperer": "/assets/icons/bosses/whisperer.png",
  "Wintertodt": "/assets/icons/bosses/wintertodt.png",
  "Yama": "/assets/icons/bosses/yama.png",
  "Zalcano": "/assets/icons/bosses/zalcano.png",
  "Zulrah": "/assets/icons/bosses/zulrah.png",
};

